framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/
            - var/tailwind/ 

when@prod:
    framework:
        asset_mapper:
            missing_import_mode: warn
