vich_uploader:
    db_driver: orm
    mappings:
        gallery_images:
            uri_prefix: /uploads/gallery
            upload_destination: '%kernel.project_dir%/public/uploads/gallery'
            # Utilise cette syntaxe Ã  la place :
            namer: Vich\UploaderBundle\Naming\UniqidNamer
